### ISSUE TITLE
New Version Should Be Uploaded to NPM

### ISSUE THREAD

**Issue by aykutaras** [shoneslab/nodejs-winrm#16]
Hi,

I see you have fixed the new Buffer issue 8 months ago. Unfortunately we could not use it because NPM package is still old. Can you create a new version with that change?

**Comment by shoneslab** [comment]
Sure. Thanks for noticing that.

**Comment by shoneslab** [comment]
Done

**Comment by aykutaras** [comment]
Thanks 👍
